services:
  knx-server:
    image: nginx:latest
    container_name: knx-server
    ports:
      - "10300:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - knx-network
    restart: always

networks:
  knx-network:
    driver: bridge
